language: ruby
cache:
  - bundler
  - yarn
services:
  - postgresql
before_install:
  - nvm install --lts
before_script:
  - bundle exec rails db:setup db:migrate db:seed
script:
  - bundle exec rspec