version: '3.4'

services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:     
      - database
      - redis
    ports: 
      - "3000:3000"
    volumes:
      - .:/rails-api-docker
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/rails-api-docker/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development

  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:5.0.7

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - web      
      - database
      - redis
    volumes:
      - .:/rails-api-docker
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/rails-api-docker/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes:
  gem_cache:
  db_data:
  node_modules: